groups:
    - bash
    - zsh
    - developer
    - java
    - chef
recipes:
    mac_os_x:
        - applications::launchrocket
        - sudoalt::default
        - osxdefaults::set_computer_name
attributes:
    dotfiles:
        vimusers:
            - root
            - dennis
        vim:
            bundle:
                - sleuth: git://github.com/tpope/vim-sleuth.git
                - sensible: git://github.com/tpope/vim-sensible.git
                - gitgutter: git://github.com/airblade/vim-gitgutter.git
                - airline: https://github.com/bling/vim-airline
                - syntastic: git://github.com/scrooloose/syntastic.git
                - nerdtree: https://github.com/scrooloose/nerdtree.git
                - vim-css-color: https://github.com/ap/vim-css-color
    git:
        name: Dennis O'Conner
        email: doconner@mygrocerydeals.com
    osxdefaults:
        computername: dennis-mbp
    authorization:
        sudo:
            users:
                - dennis
            passwordless: false
            include_sudoers_d: true
    rvm:
      installs:
        dennis:
          default_ruby: ruby-2.2.2
          rubies:
            - ruby-2.2.2
    oh_my_zsh:
      users:
        - login: dennis
