recipes:
    global:
        - applications::create_var_chef_cache
        - dotfiles::sshconfig
    mac_os_x:
        - homebrewalt::default
        - nodejs::default
        - osxdefaults::add_note_to_loginscreen
        - osxdefaults::disable_natural_scrolling
        - osxdefaults::disable_auto-correct
        - osxdefaults::enable_subpixel_font_rendering_on_non-apple_lcds
        - osxdefaults::finder_small_sidebar_icon_size
        - osxdefaults::automatically_illuminate_built-in_macbook_keyboard_in_low_light
        - osxdefaults::automatically_quit_printer_app_once_the_print_jobs_complete
        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
        - osxdefaults::disable_resume_system-wide
        - osxdefaults::save_screenshots_in_png_format
        - osxdefaults::save_screenshots_to_the_desktop
        - osxdefaults::turn_off_keyboard_illumination_when_computer_is_not_used_for_5_minutes
        - osxdefaults::finder_show_all_files
        - osxdefaults::finder_show_file_extensions
        - osxdefaults::finder_show_path_bar
        - osxdefaults::finder_show_status_bar
        - osxdefaults::make_safari_search_banners_default_to_contains_instead_of_starts_with
        - osxdefaults::dock_minimize_scale_effect
        - osxdefaults::check_for_software_updates_daily
        - osxdefaults::dock_set_magnification_on
        - osxdefaults::expand_print_panel_by_default
        - osxdefaults::expand_save_panel_by_default
attributes:
    homebrewalt:
        cask_apps:
            - google-chrome
            - java
            - 1password
            - dropbox
            - evernote
            - vlc
            - alfred
            - parallels-desktop
            - skype
            - slack
            
    osxdefaults:
      loginmessage: Property of MyGroceryDeals. If found, please call +1 (613) 224-2525.
