recipes:
    global:
        - dotfiles::gitconfig
        - applications::ssh_config
        - applications::packer
        - dotfiles::vim
        - dotfiles::workspace
    mac_os_x:
        - applications::sublime_text_3
        - applications::gnu-tar
        - osxdefaults::set_terminal_profile
        - osxdefaults::add_a_context_menu_item_for_showing_the_web_inspector_in_web_views
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::disable_disk_image_verification
        - osxdefaults::disable_gatekeeper
        - osxdefaults::disable_front_row
        - osxdefaults::enable_assistive_devices
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        - osxdefaults::increase_window_resize_speed_for_cocoa_applications
        - osxdefaults::speed_up_mission_control_animations
        - osxdefaults::tap_to_click
        - osxdefaults::do_not_show_dashboard_as_a_space
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_use_column_view_in_all_finder_windows_by_default
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_automatically_open_a_new_finder_window_when_a_volume_is_mounted
        - osxdefaults::finder_disable_the_warning_before_emptying_the_trash
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_search_the_current_folder_by_default
        - osxdefaults::finder_unhide_home
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_position_the_dock_on_the_left_side
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::mail_when_searching_do_not_include_trash
        - osxdefaults::mail_copy_email_addresses_instead_of_names_in_mail
attributes:
    homebrewalt:
        apps:
            - awscli
            - boot2docker
            - docker
            - git
            - git-extras
            - wget
            - pwgen
            - xmlstarlet
            - htop-osx
            - git-flow
            - siege
            - watch
            - rsync
        cask_apps:
            - dash
            - imageoptim
            - imagealpha
            - sourcetree
            - iterm2
            - atom
            - istat-menus
            - bartender
            - hazel
            - sonos
            - caffeine
            - tower
            - handbrake
            - slack
            - flashlight
            - couleurs
            - vagrant-manager
            - vagrant
            - virtualbox
        cask_fonts:
            - anonymous-pro
            - anonymous-pro-for-powerline
            - inconsolata-dz
            - inconsolata-dz-for-powerline
            - source-code-pro
            - source-code-pro-for-powerline
    nodejs:
        apps:
            - uglify-js
            - uglifycss
            - bower
            - grunt
            - grunt-cli
    gems:
        - sass
        - git-up
        - kstrano
        - deliver
        - crafter
    sublime_text_packages:
        -
            name: SideBarEnhancements
            source: https://github.com/titoBouzout/SideBarEnhancements
            branch: st3
        -
            name: GitGutter
            source: https://github.com/jisaacks/GitGutter.git
            branch: master
        -
            name: SCSS
            source: https://github.com/MarioRicalde/SCSS.tmbundle.git
            branch: SublimeText2
        -
            name: BracketHighlighter
            source: https://github.com/facelessuser/BracketHighlighter.git
            branch: ST3
        -
            name: Theme - Aqua
            source: https://github.com/cafarm/aqua-theme.git
            branch: master
        -
            name: Base16
            source: https://github.com/chriskempson/base16-textmate.git
            branch: master
        -
            name: ApplySyntax
            source: https://github.com/facelessuser/ApplySyntax.git
            branch: ST3
        -
            name: Theme - Flatland
            source: git://github.com/thinkpixellab/flatland.git
            branch: master
        -
            name: Haml
            source: https://github.com/phuibonhoa/handcrafted-haml-textmate-bundle.git
            branch: master
        -
            name: CoffeeScript
            source: https://github.com/aponxi/sublime-better-coffeescript.git
            branch: master
        -
            name: DashDoc
            source: https://github.com/farcaller/DashDoc.git
            branch: master
    sublime_text:
        preferences:
            draw_white_space: selection
            rulers: 
                - 80
                -120
            tab_size: 2
